// ============================================================
// CORTEX — Dados mock de pacientes de neuropsicologia
// ============================================================

// Bateria de testes comumente usados em avaliação neuropsicológica.
// Agrupados por função cognitiva. O usuário pode editar/adicionar.
const TEST_CATALOG = {
  "Intelectual": [
    { id: "wisc5", name: "WISC-V", duration: 120 },
    { id: "wais4", name: "WAIS-IV", duration: 120 },
    { id: "wasi", name: "WASI", duration: 60 },
    { id: "rbmt", name: "Matrizes Progressivas de Raven", duration: 45 },
  ],
  "Atenção": [
    { id: "d2r", name: "D2-R", duration: 20 },
    { id: "teaco", name: "TEACO-FF", duration: 15 },
    { id: "teco", name: "TECO", duration: 20 },
    { id: "trail", name: "Trail Making Test (A/B)", duration: 15 },
  ],
  "Memória": [
    { id: "rey", name: "Figuras Complexas de Rey", duration: 40 },
    { id: "rav", name: "RAVLT", duration: 45 },
    { id: "wms", name: "WMS-IV", duration: 90 },
    { id: "dgt", name: "Dígitos (direto/inverso)", duration: 10 },
  ],
  "Executivas": [
    { id: "wcst", name: "WCST", duration: 30 },
    { id: "stroop", name: "Stroop", duration: 15 },
    { id: "fdt", name: "FDT", duration: 20 },
    { id: "tfv", name: "Fluência Verbal (FAS)", duration: 10 },
    { id: "iowa", name: "Iowa Gambling Task", duration: 25 },
  ],
  "Acadêmicas": [
    { id: "tde", name: "TDE-II", duration: 60 },
    { id: "prolec", name: "PROLEC", duration: 45 },
    { id: "proesc", name: "PROESC", duration: 40 },
  ],
  "Linguagem": [
    { id: "neupsilin", name: "NEUPSILIN", duration: 40 },
    { id: "bnt", name: "Boston Naming Test", duration: 15 },
    { id: "token", name: "Token Test", duration: 15 },
  ],
  "Emocional / Comportamental": [
    { id: "bdi", name: "BDI-II", duration: 10 },
    { id: "bai", name: "BAI", duration: 10 },
    { id: "cbcl", name: "CBCL / TRF", duration: 20 },
    { id: "snap", name: "SNAP-IV", duration: 10 },
    { id: "htp", name: "HTP", duration: 30 },
  ],
};

// Etapas do fluxo (mesmas do diagrama enviado)
const STAGES = [
  { id: "anamnese",   label: "Anamnese",        color: "violet" },
  { id: "hipoteses",  label: "Hipóteses",       color: "teal" },
  { id: "checklist",  label: "Checklist",       color: "sky" },
  { id: "testes",     label: "Bateria de Testes", color: "amber" },
  { id: "correcao",   label: "Correção",        color: "orange" },
  { id: "laudo",      label: "Laudo",           color: "rose" },
  { id: "devolutiva", label: "Devolutiva",      color: "emerald" },
];

// Gera paciente mock.
function p(d) { return { id: d.id, criadoEm: d.criadoEm || "2026-03-15", ativo: d.ativo !== false, ...d }; }

const PATIENTS = [
  p({
    id: "pac-01",
    nome: "Helena Ribeiro Campos",
    idade: 9, dataNasc: "2016-08-14",
    cpf: "***.***.***-12",
    escolaridade: "4º ano EF",
    escola: "Colégio Nova Era",
    tipo: "Criança",
    responsavel: "Mariana Campos (mãe)",
    telefone: "(11) 98421-0022",
    email: "mariana.campos@email.com",
    endereco: "Rua Itambé, 420 — Higienópolis, SP",
    convenio: "Particular",
    encaminhadoPor: "Dra. Sofia Lins (neuropediatra)",
    queixa: "Dificuldade de atenção em sala, lentidão acadêmica, recusa em atividades escritas.",
    estagio: "testes",
    progresso: 58,
    inicio: "2026-02-10",
    previsaoLaudo: "2026-05-05",
    diasNaEtapa: 12,
    corAvatar: "violet",
    anamnese: {
      completude: 100,
      secoes: {
        identificacao: true, queixa: true, desenvolvimento: true,
        saude: true, familia: true, escolar: true, social: true, medicacoes: true,
      },
    },
    hipoteses: [
      { id: "h1", titulo: "TDAH apresentação desatenta", status: "em-investigacao", evidencias: ["SNAP-IV", "CBCL", "Trail Making"], peso: 3 },
      { id: "h2", titulo: "Dislexia evolutiva", status: "descartada", evidencias: ["TDE-II", "PROLEC"], peso: 2 },
      { id: "h3", titulo: "Transtorno de aprendizagem (leitura)", status: "em-investigacao", evidencias: ["PROLEC", "TDE-II"], peso: 2 },
    ],
    relatorioEscolar: { recebido: true, data: "2026-02-22", resumo: "Relatório da professora indica dificuldade em interpretação de texto e distratibilidade." },
    sessoes: [
      { data: "2026-04-22", hora: "14:00", tipo: "Aplicação", titulo: "WISC-V — Blocos 1 e 2", duracao: 90 },
      { data: "2026-04-25", hora: "09:00", tipo: "Aplicação", titulo: "D2-R + Trail Making", duracao: 60 },
      { data: "2026-04-29", hora: "14:00", tipo: "Aplicação", titulo: "TDE-II + PROLEC", duracao: 90 },
    ],
    testes: [
      { id: "wisc5",  status: "aplicado",  prevista: "2026-04-08", aplicada: "2026-04-08", obs: "" },
      { id: "rey",    status: "aplicado",  prevista: "2026-04-15", aplicada: "2026-04-15", obs: "Cópia OK, evocação reduzida." },
      { id: "d2r",    status: "agendado",  prevista: "2026-04-22", aplicada: null,         obs: "" },
      { id: "trail",  status: "agendado",  prevista: "2026-04-22", aplicada: null,         obs: "" },
      { id: "tde",    status: "agendado",  prevista: "2026-04-29", aplicada: null,         obs: "" },
      { id: "prolec", status: "agendado",  prevista: "2026-04-29", aplicada: null,         obs: "" },
      { id: "snap",   status: "aplicado",  prevista: "2026-03-20", aplicada: "2026-03-22", obs: "Respondido pelos pais." },
      { id: "cbcl",   status: "aplicado",  prevista: "2026-03-20", aplicada: "2026-03-25", obs: "" },
    ],
  }),
  p({
    id: "pac-02",
    nome: "Bernardo Teixeira Alves",
    idade: 12, dataNasc: "2013-11-03",
    cpf: "***.***.***-45",
    escolaridade: "7º ano EF",
    escola: "Colégio Santa Clara",
    tipo: "Adolescente",
    responsavel: "Ricardo Alves (pai)",
    telefone: "(11) 99132-8810",
    email: "ricardo.alves@email.com",
    endereco: "Av. Aclimação, 1101 — SP",
    convenio: "Bradesco Saúde",
    encaminhadoPor: "Dra. Carolina Mendes (psiquiatra)",
    queixa: "Queda de rendimento escolar, ansiedade, conflitos com colegas.",
    estagio: "correcao",
    progresso: 78,
    inicio: "2026-01-20",
    previsaoLaudo: "2026-04-30",
    diasNaEtapa: 6,
    corAvatar: "teal",
    anamnese: { completude: 100, secoes: { identificacao: true, queixa: true, desenvolvimento: true, saude: true, familia: true, escolar: true, social: true, medicacoes: true } },
    hipoteses: [
      { id: "h1", titulo: "Transtorno de Ansiedade Generalizada", status: "confirmada", evidencias: ["BAI", "CBCL", "Entrevista"], peso: 3 },
      { id: "h2", titulo: "TDAH combinado", status: "em-investigacao", evidencias: ["SNAP-IV", "WCST"], peso: 2 },
    ],
    relatorioEscolar: { recebido: true, data: "2026-02-01", resumo: "Coordenação aponta ansiedade em avaliações e evitação social." },
    sessoes: [
      { data: "2026-04-23", hora: "16:00", tipo: "Correção", titulo: "Correção WISC-V + WCST", duracao: 120 },
      { data: "2026-04-30", hora: "10:00", tipo: "Devolutiva", titulo: "Devolutiva aos pais", duracao: 60 },
    ],
    testes: [
      { id: "wisc5", status: "aplicado", prevista: "2026-03-01", aplicada: "2026-03-05", obs: "" },
      { id: "wcst",  status: "aplicado", prevista: "2026-03-10", aplicada: "2026-03-12", obs: "" },
      { id: "stroop",status: "aplicado", prevista: "2026-03-15", aplicada: "2026-03-15", obs: "" },
      { id: "bai",   status: "aplicado", prevista: "2026-03-01", aplicada: "2026-03-01", obs: "Score elevado." },
      { id: "bdi",   status: "aplicado", prevista: "2026-03-01", aplicada: "2026-03-01", obs: "" },
      { id: "tde",   status: "aplicado", prevista: "2026-03-20", aplicada: "2026-03-22", obs: "" },
      { id: "rey",   status: "aplicado", prevista: "2026-03-25", aplicada: "2026-03-26", obs: "" },
    ],
  }),
  p({
    id: "pac-03",
    nome: "Antonia Lacerda Moraes",
    idade: 34, dataNasc: "1991-04-22",
    cpf: "***.***.***-78",
    escolaridade: "Ensino Superior Completo",
    escola: "Gerente de Projetos",
    tipo: "Adulto",
    responsavel: "—",
    telefone: "(11) 97321-4455",
    email: "antonia.lm@email.com",
    endereco: "Rua Peixoto Gomide, 500 — SP",
    convenio: "SulAmérica",
    encaminhadoPor: "Dr. Henrique Vasconcelos (neurologista)",
    queixa: "Esquecimentos frequentes, dificuldade de concentração em reuniões, fadiga mental após COVID.",
    estagio: "laudo",
    progresso: 92,
    inicio: "2025-12-05",
    previsaoLaudo: "2026-04-26",
    diasNaEtapa: 18,
    corAvatar: "rose",
    anamnese: { completude: 100, secoes: { identificacao: true, queixa: true, desenvolvimento: true, saude: true, familia: true, escolar: true, social: true, medicacoes: true } },
    hipoteses: [
      { id: "h1", titulo: "Síndrome pós-COVID (fog cognitivo)", status: "confirmada", evidencias: ["NEUPSILIN", "RAVLT", "Dígitos"], peso: 4 },
      { id: "h2", titulo: "Transtorno depressivo leve", status: "em-investigacao", evidencias: ["BDI-II"], peso: 2 },
    ],
    relatorioEscolar: { recebido: false, data: null, resumo: "" },
    sessoes: [
      { data: "2026-04-24", hora: "11:00", tipo: "Laudo", titulo: "Fechamento do laudo", duracao: 120 },
    ],
    testes: [
      { id: "wais4",     status: "aplicado", prevista: "2026-02-01", aplicada: "2026-02-03", obs: "" },
      { id: "neupsilin", status: "aplicado", prevista: "2026-02-10", aplicada: "2026-02-11", obs: "Memória de trabalho rebaixada." },
      { id: "rav",       status: "aplicado", prevista: "2026-02-15", aplicada: "2026-02-17", obs: "Curva de aprendizagem lenta." },
      { id: "rey",       status: "aplicado", prevista: "2026-02-20", aplicada: "2026-02-20", obs: "" },
      { id: "stroop",    status: "aplicado", prevista: "2026-03-01", aplicada: "2026-03-01", obs: "" },
      { id: "wcst",      status: "aplicado", prevista: "2026-03-08", aplicada: "2026-03-10", obs: "" },
      { id: "bdi",       status: "aplicado", prevista: "2026-02-01", aplicada: "2026-02-01", obs: "" },
      { id: "bai",       status: "aplicado", prevista: "2026-02-01", aplicada: "2026-02-01", obs: "" },
    ],
  }),
  p({
    id: "pac-04",
    nome: "Joaquim Pessanha Reis",
    idade: 7, dataNasc: "2018-06-29",
    cpf: "***.***.***-09",
    escolaridade: "2º ano EF",
    escola: "Escola Viva",
    tipo: "Criança",
    responsavel: "Paula Reis (mãe)",
    telefone: "(11) 98877-1122",
    email: "paula.reis@email.com",
    endereco: "Alameda Jaú, 880 — SP",
    convenio: "Particular",
    encaminhadoPor: "Coordenação escolar",
    queixa: "Suspeita de TEA. Dificuldade em interações sociais e interesses restritos.",
    estagio: "anamnese",
    progresso: 15,
    inicio: "2026-04-05",
    previsaoLaudo: "2026-07-30",
    diasNaEtapa: 17,
    corAvatar: "amber",
    anamnese: { completude: 45, secoes: { identificacao: true, queixa: true, desenvolvimento: true, saude: false, familia: false, escolar: true, social: false, medicacoes: false } },
    hipoteses: [
      { id: "h1", titulo: "Transtorno do Espectro Autista nível 1", status: "em-investigacao", evidencias: [], peso: 3 },
    ],
    relatorioEscolar: { recebido: false, data: null, resumo: "Solicitado em 12/04." },
    sessoes: [
      { data: "2026-04-22", hora: "09:30", tipo: "Anamnese", titulo: "Anamnese — sessão 2 (pais)", duracao: 60 },
      { data: "2026-04-26", hora: "10:00", tipo: "Anamnese", titulo: "Anamnese — sessão 3 (criança)", duracao: 45 },
    ],
    testes: [],
  }),
  p({
    id: "pac-05",
    nome: "Laís Fontenele Barros",
    idade: 16, dataNasc: "2009-09-18",
    cpf: "***.***.***-33",
    escolaridade: "1º ano EM",
    escola: "Colégio Oswald",
    tipo: "Adolescente",
    responsavel: "Juliana Fontenele (mãe)",
    telefone: "(11) 98000-3311",
    email: "julianafb@email.com",
    endereco: "Rua Cardeal Arcoverde, 1234 — SP",
    convenio: "Particular",
    encaminhadoPor: "Dra. Marina Prado (psicóloga)",
    queixa: "Dificuldades em matemática persistentes, ansiedade de desempenho.",
    estagio: "hipoteses",
    progresso: 28,
    inicio: "2026-03-15",
    previsaoLaudo: "2026-06-20",
    diasNaEtapa: 4,
    corAvatar: "sky",
    anamnese: { completude: 85, secoes: { identificacao: true, queixa: true, desenvolvimento: true, saude: true, familia: true, escolar: true, social: false, medicacoes: true } },
    hipoteses: [
      { id: "h1", titulo: "Discalculia", status: "em-investigacao", evidencias: ["TDE-II (prev.)"], peso: 3 },
      { id: "h2", titulo: "Transtorno de ansiedade", status: "em-investigacao", evidencias: [], peso: 2 },
    ],
    relatorioEscolar: { recebido: true, data: "2026-03-28", resumo: "" },
    sessoes: [
      { data: "2026-04-23", hora: "15:00", tipo: "Planejamento", titulo: "Revisão de hipóteses + montagem de bateria", duracao: 60 },
    ],
    testes: [],
  }),
  p({
    id: "pac-06",
    nome: "Rafael Coutinho Serra",
    idade: 42, dataNasc: "1983-01-14",
    cpf: "***.***.***-55",
    escolaridade: "Mestrado",
    escola: "Advogado",
    tipo: "Adulto",
    responsavel: "—",
    telefone: "(11) 99555-2200",
    email: "rafael.cs@email.com",
    endereco: "Rua Haddock Lobo, 700 — SP",
    convenio: "Amil",
    encaminhadoPor: "Auto-encaminhamento",
    queixa: "Suspeita de TDAH na vida adulta, dificuldade de organização e prazos.",
    estagio: "testes",
    progresso: 42,
    inicio: "2026-03-01",
    previsaoLaudo: "2026-06-01",
    diasNaEtapa: 9,
    corAvatar: "emerald",
    anamnese: { completude: 100, secoes: { identificacao: true, queixa: true, desenvolvimento: true, saude: true, familia: true, escolar: true, social: true, medicacoes: true } },
    hipoteses: [
      { id: "h1", titulo: "TDAH apresentação combinada (adulto)", status: "em-investigacao", evidencias: ["ASRS", "WAIS-IV (parcial)"], peso: 3 },
    ],
    relatorioEscolar: { recebido: false, data: null, resumo: "N/A — adulto" },
    sessoes: [
      { data: "2026-04-22", hora: "19:00", tipo: "Aplicação", titulo: "WAIS-IV — Bloco 2", duracao: 90 },
      { data: "2026-04-28", hora: "19:00", tipo: "Aplicação", titulo: "Stroop + Trail + FDT", duracao: 60 },
    ],
    testes: [
      { id: "wais4", status: "aplicado", prevista: "2026-04-15", aplicada: "2026-04-15", obs: "Metade 1 concluída." },
      { id: "stroop", status: "agendado", prevista: "2026-04-28", aplicada: null, obs: "" },
      { id: "trail", status: "agendado", prevista: "2026-04-28", aplicada: null, obs: "" },
      { id: "fdt", status: "agendado", prevista: "2026-04-28", aplicada: null, obs: "" },
      { id: "wcst", status: "pendente", prevista: "2026-05-05", aplicada: null, obs: "" },
    ],
  }),
  p({
    id: "pac-07",
    nome: "Mirella Salles Pires",
    idade: 8, dataNasc: "2017-12-10",
    cpf: "***.***.***-71",
    escolaridade: "3º ano EF",
    escola: "Colégio Arquidiocesano",
    tipo: "Criança",
    responsavel: "Tatiana Salles (mãe)",
    telefone: "(11) 99100-8090",
    email: "tsalles@email.com",
    endereco: "Rua Artur de Azevedo, 222 — SP",
    convenio: "Particular",
    encaminhadoPor: "Dra. Clara Iglesias (fonoaudióloga)",
    queixa: "Trocas na escrita, leitura silabada.",
    estagio: "devolutiva",
    progresso: 100,
    inicio: "2025-11-10",
    previsaoLaudo: "2026-04-15",
    diasNaEtapa: 2,
    corAvatar: "orange",
    anamnese: { completude: 100, secoes: { identificacao: true, queixa: true, desenvolvimento: true, saude: true, familia: true, escolar: true, social: true, medicacoes: true } },
    hipoteses: [
      { id: "h1", titulo: "Dislexia evolutiva", status: "confirmada", evidencias: ["PROLEC", "TDE-II", "NEUPSILIN"], peso: 4 },
    ],
    relatorioEscolar: { recebido: true, data: "2025-12-01", resumo: "" },
    sessoes: [
      { data: "2026-04-25", hora: "16:30", tipo: "Devolutiva", titulo: "Devolutiva aos pais + escola", duracao: 90 },
    ],
    testes: [],
  }),
  p({
    id: "pac-08",
    nome: "Tobias Nakagawa Veiga",
    idade: 14, dataNasc: "2011-05-01",
    cpf: "***.***.***-19",
    escolaridade: "9º ano EF",
    escola: "Escola Móbile",
    tipo: "Adolescente",
    responsavel: "Bruno Veiga (pai)",
    telefone: "(11) 98741-6500",
    email: "bveiga@email.com",
    endereco: "Av. Brigadeiro, 2200 — SP",
    convenio: "Particular",
    encaminhadoPor: "Dr. Otávio Matos (psiquiatra infantil)",
    queixa: "Dificuldades em funções executivas, organização de estudos.",
    estagio: "correcao",
    progresso: 72,
    inicio: "2026-02-14",
    previsaoLaudo: "2026-05-10",
    diasNaEtapa: 14,
    corAvatar: "violet",
    anamnese: { completude: 100, secoes: { identificacao: true, queixa: true, desenvolvimento: true, saude: true, familia: true, escolar: true, social: true, medicacoes: true } },
    hipoteses: [
      { id: "h1", titulo: "TDAH desatento + déficit executivo", status: "em-investigacao", evidencias: ["WISC-V", "WCST", "Trail B"], peso: 3 },
    ],
    relatorioEscolar: { recebido: true, data: "2026-02-28", resumo: "" },
    sessoes: [],
    testes: [
      { id: "wisc5", status: "aplicado", prevista: "2026-03-05", aplicada: "2026-03-07", obs: "" },
      { id: "wcst",  status: "aplicado", prevista: "2026-03-15", aplicada: "2026-03-17", obs: "" },
      { id: "trail", status: "aplicado", prevista: "2026-03-15", aplicada: "2026-03-17", obs: "" },
      { id: "stroop",status: "aplicado", prevista: "2026-03-20", aplicada: "2026-03-20", obs: "" },
      { id: "tfv",   status: "aplicado", prevista: "2026-03-22", aplicada: "2026-03-22", obs: "" },
    ],
  }),
  p({
    id: "pac-09",
    nome: "Cecília Moraes Bittencourt",
    idade: 68, dataNasc: "1957-03-03",
    cpf: "***.***.***-40",
    escolaridade: "Ensino Médio",
    escola: "Aposentada (professora)",
    tipo: "Idoso",
    responsavel: "Fernanda Bittencourt (filha)",
    telefone: "(11) 99200-7070",
    email: "fernandabb@email.com",
    endereco: "Rua Estados Unidos, 1500 — SP",
    convenio: "Unimed",
    encaminhadoPor: "Dr. Alessandro Peres (geriatra)",
    queixa: "Esquecimentos progressivos, suspeita de CCL/demência inicial.",
    estagio: "testes",
    progresso: 48,
    inicio: "2026-03-10",
    previsaoLaudo: "2026-05-30",
    diasNaEtapa: 8,
    corAvatar: "teal",
    anamnese: { completude: 100, secoes: { identificacao: true, queixa: true, desenvolvimento: true, saude: true, familia: true, escolar: true, social: true, medicacoes: true } },
    hipoteses: [
      { id: "h1", titulo: "Comprometimento Cognitivo Leve amnéstico", status: "em-investigacao", evidencias: ["RAVLT", "NEUPSILIN"], peso: 3 },
      { id: "h2", titulo: "Depressão em idoso", status: "em-investigacao", evidencias: ["BDI-II"], peso: 2 },
    ],
    relatorioEscolar: { recebido: false, data: null, resumo: "N/A" },
    sessoes: [
      { data: "2026-04-23", hora: "10:30", tipo: "Aplicação", titulo: "WAIS-IV + RAVLT", duracao: 120 },
    ],
    testes: [
      { id: "neupsilin", status: "aplicado", prevista: "2026-04-01", aplicada: "2026-04-02", obs: "" },
      { id: "rav",       status: "aplicado", prevista: "2026-04-08", aplicada: "2026-04-08", obs: "Curva rebaixada." },
      { id: "wais4",     status: "agendado", prevista: "2026-04-23", aplicada: null,         obs: "" },
      { id: "rey",       status: "pendente", prevista: "2026-05-01", aplicada: null,         obs: "" },
    ],
  }),
  p({
    id: "pac-10",
    nome: "Davi Queiroga Lins",
    idade: 19, dataNasc: "2006-07-28",
    cpf: "***.***.***-62",
    escolaridade: "Cursinho pré-vestibular",
    escola: "Anglo",
    tipo: "Adolescente",
    responsavel: "Renata Lins (mãe)",
    telefone: "(11) 98654-9988",
    email: "davi.lins@email.com",
    endereco: "Rua Mourato Coelho, 900 — SP",
    convenio: "Particular",
    encaminhadoPor: "Dra. Beatriz Noguchi (psicóloga)",
    queixa: "Travamentos em provas, ansiedade de desempenho, insônia.",
    estagio: "checklist",
    progresso: 35,
    inicio: "2026-03-25",
    previsaoLaudo: "2026-06-15",
    diasNaEtapa: 3,
    corAvatar: "amber",
    anamnese: { completude: 100, secoes: { identificacao: true, queixa: true, desenvolvimento: true, saude: true, familia: true, escolar: true, social: true, medicacoes: true } },
    hipoteses: [
      { id: "h1", titulo: "Transtorno de Ansiedade de Desempenho", status: "em-investigacao", evidencias: ["BAI", "Entrevista"], peso: 3 },
    ],
    relatorioEscolar: { recebido: true, data: "2026-04-01", resumo: "" },
    sessoes: [],
    testes: [],
  }),
  p({
    id: "pac-11",
    nome: "Beatriz Haddad Carneiro",
    idade: 11, dataNasc: "2014-10-06",
    cpf: "***.***.***-27",
    escolaridade: "6º ano EF",
    escola: "Colégio Dante",
    tipo: "Criança",
    responsavel: "Lucas Haddad (pai)",
    telefone: "(11) 99800-1200",
    email: "lucash@email.com",
    endereco: "Rua Tutoia, 300 — SP",
    convenio: "Particular",
    encaminhadoPor: "Neuropediatra",
    queixa: "Bloqueios em leitura, troca de palavras, escrita lenta.",
    estagio: "testes",
    progresso: 62,
    inicio: "2026-02-18",
    previsaoLaudo: "2026-05-18",
    diasNaEtapa: 5,
    corAvatar: "rose",
    anamnese: { completude: 100, secoes: { identificacao: true, queixa: true, desenvolvimento: true, saude: true, familia: true, escolar: true, social: true, medicacoes: true } },
    hipoteses: [
      { id: "h1", titulo: "Dislexia evolutiva", status: "em-investigacao", evidencias: ["PROLEC", "TDE-II"], peso: 3 },
    ],
    relatorioEscolar: { recebido: true, data: "2026-03-05", resumo: "" },
    sessoes: [
      { data: "2026-04-24", hora: "15:00", tipo: "Aplicação", titulo: "PROLEC completo", duracao: 60 },
    ],
    testes: [
      { id: "wisc5",  status: "aplicado", prevista: "2026-03-01", aplicada: "2026-03-02", obs: "" },
      { id: "tde",    status: "aplicado", prevista: "2026-03-20", aplicada: "2026-03-20", obs: "" },
      { id: "prolec", status: "agendado", prevista: "2026-04-24", aplicada: null,         obs: "" },
      { id: "proesc", status: "pendente", prevista: "2026-05-02", aplicada: null,         obs: "" },
    ],
  }),
  p({
    id: "pac-12",
    nome: "Gustavo Antunes Prado",
    idade: 10, dataNasc: "2015-02-19",
    cpf: "***.***.***-88",
    escolaridade: "5º ano EF",
    escola: "Escola Projeto",
    tipo: "Criança",
    responsavel: "Isabela Prado (mãe)",
    telefone: "(11) 97777-6655",
    email: "isa.prado@email.com",
    endereco: "Rua Aspicuelta, 140 — SP",
    convenio: "Particular",
    encaminhadoPor: "Psicopedagoga",
    queixa: "Comportamento agitado, dificuldade de regular emoções.",
    estagio: "hipoteses",
    progresso: 22,
    inicio: "2026-03-20",
    previsaoLaudo: "2026-06-30",
    diasNaEtapa: 22, ativo: true,
    corAvatar: "sky",
    anamnese: { completude: 70, secoes: { identificacao: true, queixa: true, desenvolvimento: true, saude: true, familia: true, escolar: false, social: false, medicacoes: true } },
    hipoteses: [
      { id: "h1", titulo: "TDAH hiperativo/impulsivo", status: "em-investigacao", evidencias: [], peso: 2 },
      { id: "h2", titulo: "Transtorno Opositor Desafiador", status: "em-investigacao", evidencias: [], peso: 2 },
    ],
    relatorioEscolar: { recebido: false, data: null, resumo: "Solicitado." },
    sessoes: [],
    testes: [],
  }),
];

// Agenda agregada (derivada dos sessoes de cada paciente)
function buildCalendar(patients) {
  const all = [];
  patients.forEach(pac => (pac.sessoes || []).forEach(s => all.push({ ...s, pacId: pac.id, pacNome: pac.nome, corAvatar: pac.corAvatar })));
  return all.sort((a,b) => (a.data + a.hora).localeCompare(b.data + b.hora));
}

window.CORTEX_DATA = {
  TEST_CATALOG,
  STAGES,
  PATIENTS,
  CALENDAR: buildCalendar(PATIENTS),
  TODAY: "2026-04-22",
};
